### ISSUE TITLE
How can I update the doc indexes for 2019.3?

### ISSUE THREAD

**Issue by jschmidt42** [sttz/unity-quicksearch-docs#2]
Hi, how can I update the doc indexes for 2019.3? Also would it be possible to have the indexes for multiple versions at the same time?

I love this quick search extension!

**Comment by sttz** [comment]
I just pushed an updated with an index for 2019.2, I'll update the index to 2019.3 when that's been released.

The package includes code to generate the index from the downloaded documentation (see Window » Quick Search Docs » Generate Index) but it'll just use the first index that the asset database returns, which means the bundled index likely has to be removed for consistent results.

I'm planning to make generating the index easier as well as having indices for multiple versions and being able to select which you want to use. But that requires figuring out where to store the indices and how to select the one to use, which I haven't gotten around to yet.

**Comment by jschmidt42** [comment]
Ok perfect. Great work again.

**Comment by sttz** [comment]
The latest version now bundles indices for 2018.4, 2019.1, 2019.2, 2019.3 and 2020.1.

It's also possible to generate indices yourself and then place them in the project root, Unity installation root or common data path to override the bundled indices.

The latest version also supports offline documentation and opens the right online documentation for the current Unity version.
